In [1]:
# Import the NumPy library
import numpy as np
# Import the Pandas library
import pandas as pd

In [2]:
# Create a dictionary containing employee information
employee_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"],
    "Gender": ["M", "F", "M", "F", "F"],
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"],
    "Age": [25, 27, 29, 31, 30]
}

In [3]:
# Convert the dictionary into a DataFrame
employee_df = pd.DataFrame(employee_data)

In [4]:
# Display the Employee DataFrame
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [5]:
# Save the Employee DataFrame as a CSV file
employee_df.to_csv("Employee.csv", index=False)

In [6]:
# Create a dictionary containing seniority level information
seniority_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Designation Level": [2, 2, 3, 2, 3]
}

In [7]:
# Convert the dictionary into a DataFrame
seniority_df = pd.DataFrame(seniority_data)

In [8]:
# Display the Seniority Level DataFrame
seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [9]:
# Save the Seniority Level DataFrame as a CSV file
seniority_df.to_csv("Seniority_Level.csv", index=False)

In [10]:
# Create a dictionary containing project information
project_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005", "A002", "A005", "A003", "A001", "A003", "A001", "A004", "A004", "A005"],
    "Project": [
        "Project 1", "Project 2", "Project 3", "Project 4",
        "Project 5", "Project 6", "Project 7", "Project 8",
        "Project 9", "Project 10", "Project 11", "Project 12",
        "Project 13", "Project 14"
    ],
    "Cost": [
        1002000, 2000000, 4500000, 5500000,
        np.nan, 680000, 400000, 350000,
        np.nan, 300000, 2000000, 1000000,
        3000000, 200000
    ],
    "Status": [
        "Finished", "Ongoing", "Finished", "Ongoing",
        "Finished", "Failed", "Finished", "Failed",
        "Ongoing", "Finished", "Failed", "Ongoing",
        "Finished", "Finished"
    ]
}

In [11]:
# Convert the dictionary into a DataFrame
project_df = pd.DataFrame(project_data)

In [12]:
# Display the Project DataFrame
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [13]:
# Save the Project DataFrame as a CSV file
project_df.to_csv("Project.csv", index=False)

In [14]:
# Read the Employee CSV file
employee = pd.read_csv("Employee.csv")

# Read the Seniority Level CSV file
seniority = pd.read_csv("Seniority_Level.csv")

# Read the Project CSV file
project = pd.read_csv("Project.csv")

In [15]:
# Display the Project DataFrame
project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [16]:
# Check the number of missing values in each column
project.isnull().sum()

ID         0
Project    0
Cost       2
Status     0
dtype: int64

In [17]:
# Loop through each row in the Project DataFrame
for i in range(len(project)):
    
    # Check if the Cost value in the current row is missing
    if pd.isna(project.loc[i, "Cost"]):
        
        # Calculate the average of all previous Cost values
        running_average = project.loc[:i-1, "Cost"].mean()
        
        # Replace the missing Cost value with the running average
        project.loc[i, "Cost"] = running_average

In [18]:
# Display the updated Project DataFrame
project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [19]:
# Display the Employee DataFrame
employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [20]:
# Split the Name column into First Name and Last Name
employee[["First Name", "Last Name"]] = employee["Name"].str.split(" ", expand=True)

In [21]:
# Remove the original Name column
employee.drop("Name", axis=1, inplace=True)

In [22]:
# Display the updated Employee DataFrame
employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [23]:
# Merge Employee and Seniority DataFrames using the ID column
employee_seniority = pd.merge(employee, seniority, on="ID")

In [24]:
# Merge the Employee-Seniority DataFrame with the Project DataFrame using the ID column
Final = pd.merge(employee_seniority, project, on="ID")

In [25]:
# Display the Final DataFrame
Final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000.0,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2210312.5,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2000000.0,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000.0,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,680000.0,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000.0,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,350000.0,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000.0,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.0,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.0,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.0,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500.0,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.0,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.0,Finished

In [26]:
# Create a Bonus column with 0 as the default value
Final["Bonus"] = 0

In [27]:
# Give a 5% bonus to employees who have finished their projects
Final.loc[Final["Status"] == "Finished", "Bonus"] = Final["Cost"] * 0.05

In [28]:
# Display the updated Final DataFrame
Final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000.0,Finished,50100
1,A001,M,Paris,25,John,Alter,2,Project 9,2210312.5,Ongoing,0
2,A001,M,Paris,25,John,Alter,2,Project 11,2000000.0,Failed,0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,680000.0,Failed,0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000.0,Finished,225000
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,350000.0,Failed,0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000.0,Finished,15000
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.0,Ongoing,0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.0,Ongoing,0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.0,Finished,150000
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500.0,Finished,162525
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.0,Finished,20000
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.0,Finished,10000

In [29]:
# Find the IDs of employees who have at least one project with status "Failed"
failed_ids = Final.loc[Final["Status"] == "Failed", "ID"].unique()

# Demote these employees by 1 level (level number increases because 1 is the highest and 4 the lowest)
Final.loc[Final["ID"].isin(failed_ids), "Designation Level"] += 1

In [30]:
# Remove employee records whose Designation Level is above 4 (they lose eligibility to head projects)
Final = Final[Final["Designation Level"] <= 4].copy()

In [31]:
# Display the updated Final DataFrame
Final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,3,Project 1,1002000.0,Finished,50100
1,A001,M,Paris,25,John,Alter,3,Project 9,2210312.5,Ongoing,0
2,A001,M,Paris,25,John,Alter,3,Project 11,2000000.0,Failed,0
3,A002,F,London,27,Alice,Luxumberg,3,Project 2,2000000.0,Ongoing,0
4,A002,F,London,27,Alice,Luxumberg,3,Project 6,680000.0,Failed,0
5,A003,M,Berlin,29,Tom,Sabestine,4,Project 3,4500000.0,Finished,225000
6,A003,M,Berlin,29,Tom,Sabestine,4,Project 8,350000.0,Failed,0
7,A003,M,Berlin,29,Tom,Sabestine,4,Project 10,300000.0,Finished,15000
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.0,Ongoing,0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.0,Ongoing,0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.0,Finished,150000
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500.0,Finished,162525
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.0,Finished,20000
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.0,Finished,10000

In [32]:
# Add "Mr." to the First Name of male employees
Final.loc[Final["Gender"] == "M", "First Name"] = "Mr. " + Final["First Name"]

In [33]:
# Add "Mrs." to the First Name of female employees
Final.loc[Final["Gender"] == "F", "First Name"] = "Mrs. " + Final["First Name"]

In [34]:
# Remove the Gender column
Final.drop("Gender", axis=1, inplace=True)

In [35]:
# Display the updated Final DataFrame
Final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,3,Project 1,1002000.0,Finished,50100
1,A001,Paris,25,Mr. John,Alter,3,Project 9,2210312.5,Ongoing,0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2000000.0,Failed,0
3,A002,London,27,Mrs. Alice,Luxumberg,3,Project 2,2000000.0,Ongoing,0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0
5,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 3,4500000.0,Finished,225000
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,350000.0,Failed,0
7,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 10,300000.0,Finished,15000
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5500000.0,Ongoing,0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1000000.0,Ongoing,0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3000000.0,Finished,150000
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3250500.0,Finished,162525
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,400000.0,Finished,20000
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,200000.0,Finished,10000

In [36]:
# Get the unique employees (one row per ID) with their Age
for emp_id in Final["ID"].unique():

    # Read the age of the current employee
    age = Final.loc[Final["ID"] == emp_id, "Age"].iloc[0]

    # IF the employee is older than 29 years
    if age > 29:

        # Promote by 1 level (level number decreases because 1 is the highest grade)
        Final.loc[Final["ID"] == emp_id, "Designation Level"] -= 1

In [37]:
# Display the updated Final DataFrame
Final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,3,Project 1,1002000.0,Finished,50100
1,A001,Paris,25,Mr. John,Alter,3,Project 9,2210312.5,Ongoing,0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2000000.0,Failed,0
3,A002,London,27,Mrs. Alice,Luxumberg,3,Project 2,2000000.0,Ongoing,0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0
5,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 3,4500000.0,Finished,225000
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,350000.0,Failed,0
7,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 10,300000.0,Finished,15000
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3250500.0,Finished,162525
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,400000.0,Finished,20000
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,200000.0,Finished,10000

In [38]:
# Calculate the total project cost for each employee
TotalProjCost = Final.groupby(["ID", "First Name"], as_index=False)["Cost"].sum()

In [39]:
# Rename the Cost column to Total Cost
TotalProjCost.rename(columns={"Cost": "Total Cost"}, inplace=True)

In [40]:
# Display the Total Project Cost DataFrame
TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

In [41]:
# Create a new DataFrame containing employees whose City contains the letter "o"
city_o = Final[Final["City"].str.contains("o", case=False)]

In [42]:
# Display the filtered DataFrame
city_o

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,3,Project 2,2000000.0,Ongoing,0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000